# Generated by Django 4.2.2 on 2024-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
