# Generated by Django 4.2.2 on 2024-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_streamuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
